# docker build -t nasa-feedhandler -f microservices/nasa/dockerfile .
# docker run -it --rm -e API_KEY=""

FROM python:3.9-slim-buster

WORKDIR /app

ARG API_KEY

ENV API_KEY=${API_KEY}

# Install python requirements
RUN pip install --no-input \
    python-dotenv \
    requests

# Copy necessary scripts from host to container
COPY microservices/nasa/*.py /app/nasa/

VOLUME ["/data"]

# Run th python module with environment variables set from outside the container
CMD ["python", "-m", "nasa"]