# docker build -t nasa-feedhandler -f microservices/nasa/dockerfile .
# docker run -it --rm -e API_KEY="" -t nasa-feedhandler

FROM python:3.9-slim-buster

WORKDIR /code

# Install python requirements
RUN pip install --no-input \
    python-dotenv \
    requests

# Copy necessary scripts from host to container
COPY microservices/nasa/*.py /code/microservices/nasa/

VOLUME ["/data"]

# Run th python module with environment variables set from outside the container
CMD ["python3", "-m", "microservices.nasa"]