name: ROS2 Docker Build and Push

on:
  push:
    branches:
      - main
    paths:
      - 'ws/src/pointcloud_detection/**'
      - 'ws/pointcloud.Dockerfile'
      - '.github/workflows/ros_build.yml'

env:
  APP_NAME: pointcloud_detection
  RELEASE_VERSION: latest

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build image
        run: |
          cd ws
          docker build -t ${{ env.APP_NAME }} -f pointcloud.Dockerfile .

      - name: Tag image
        run: docker tag ${{ env.APP_NAME }} ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REGISTRY }}:${{ env.RELEASE_VERSION }}

      - name: Push image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REGISTRY }}:${{ env.RELEASE_VERSION }}

      # debug step
      - name: Verify image
        run: docker images | grep ${{ env.APP_NAME }}